export const appTheme = {
  token: {
    colorPrimary: '#1677ff',
    colorBgLayout: '#ffffff',
    colorBgContainer: '#ffffff',
    colorTextHeading: '#0f172a',
    borderRadius: 6,
    controlHeight: 30,
    fontSize: 13,
    boxShadow: 'none',
    boxShadowSecondary: 'none',
    colorBorder: '#e2e8f0',
    colorBorderSecondary: '#e2e8f0',
    paddingContentHorizontal: 12,
    paddingContentVertical: 8,
    fontFamily: "'Roboto', sans-serif",
  },
  components: {
    Card: {
      boxShadowTertiary: 'none',
      paddingLG: 16,
    },
    Layout: {
      headerBg: 'transparent',
      headerPadding: '0 16px',
      headerHeight: 50,
      siderBg: '#ffffff',
      bodyBg: '#ffffff',
    },
    Menu: {
      activeBarBorderWidth: 0,
      itemBorderRadius: 6,
      itemHeight: 34,
      itemMarginInline: 4,
      itemPaddingInline: 8,
      itemSelectedBg: '#e6f4ff',
      itemSelectedColor: '#1677ff',
      itemHoverBg: '#f1f5f9',
      itemActiveBg: '#eef6ff',
      subMenuItemBg: 'transparent',
      iconSize: 15,
      collapsedIconSize: 16,
      groupTitleColor: '#94a3b8',
      groupTitleFontSize: 10,
    },
    Table: {
      headerBg: '#f8fafc',
      headerColor: '#475569',
      borderColor: '#e2e8f0',
      cellPaddingBlock: 5,
      cellPaddingInline: 10,
      rowHoverBg: '#f1f5f9',
    },
    Button: {
      primaryShadow: 'none',
      defaultShadow: 'none',
      controlHeight: 30,
    },
  },
}
