export const appTheme = {
  token: {
    colorPrimary: '#1677ff',
    colorBgLayout: '#ffffff',
    colorBgContainer: '#ffffff',
    colorTextHeading: '#1f2937',
    borderRadius: 8,
    controlHeight: 32,
    boxShadow: 'none',
    boxShadowSecondary: 'none',
    colorBorder: '#e2e8f0',
    colorBorderSecondary: '#e8eef5',
    paddingContentHorizontal: 16,
    paddingContentVertical: 12,
    fontFamily: "'Inter', sans-serif",
  },
  components: {
    Card: {
      boxShadowTertiary: 'none',
      paddingLG: 24,
    },
    Layout: {
      headerBg: 'transparent',
      headerPadding: '0 32px',
      headerHeight: 64,
      siderBg: '#f8fafc',
      bodyBg: '#ffffff',
    },
    Menu: {
      activeBarBorderWidth: 0,
      itemBorderRadius: 8,
      itemHeight: 38,
      itemMarginInline: 8,
      itemPaddingInline: 12,
      itemSelectedBg: '#e6f4ff',
      itemSelectedColor: '#1677ff',
      itemHoverBg: '#f1f5f9',
      itemActiveBg: '#eef6ff',
      subMenuItemBg: 'transparent',
      iconSize: 16,
      collapsedIconSize: 18,
      groupTitleColor: '#94a3b8',
      groupTitleFontSize: 11,
    },
    Table: {
      headerBg: '#f8fafc',
      headerColor: '#475569',
      borderColor: '#e2e8f0',
      cellPaddingBlock: 6,
      cellPaddingInline: 12,
      rowHoverBg: '#f1f5f9',
    },
    Button: {
      primaryShadow: 'none',
      defaultShadow: 'none',
      controlHeight: 32,
    },
  },
}
