-- AlterTable
ALTER TABLE "courses" ALTER COLUMN "credits" SET DATA TYPE DOUBLE PRECISION;
ALTER TABLE "courses" ALTER COLUMN "theory_credits" SET DATA TYPE DOUBLE PRECISION;
ALTER TABLE "courses" ALTER COLUMN "practice_credits" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "curricula" ALTER COLUMN "total_credits" SET DATA TYPE DOUBLE PRECISION;
